[package]
name = "bfs"
version = "0.1.0"
authors = ["Pauli Jaakkola <pauli.jaakkola@iki.fi>"]

[dependencies]
rustyline = "6.0"
libc = "0.2"
docopt = "0.7"
rustc-serialize = "0.3"
dynasm = "0.6.0"
dynasmrt = "0.6.0"

